INSERT INTO currency_ VALUES
    ('AAD', '$'),
    ('ALL', 'Lek'),
    ('AFN', '؋'),
    ('AMD', '֏'),
    ('AOA', 'Kz'),
    ('ARS', '$'),
    ('AWG', 'ƒ'),
    ('AUD', '$'),
    ('AZN', '₼'),
    ('BHD', 'د.ب'),
    ('BSD', '$'),
    ('BBD', '$'),
    ('BDT', '৳'),
    ('BIF', 'FBu'),
    ('BTN', 'Nu.'),
    ('BYN', 'Br'),
    ('BZD', 'BZ$'),
    ('BMD', '$'),
    ('BOB', '$b'),
    ('BAM', 'KM'),
    ('BWP', 'P'),
    ('BGN', 'лв'),
    ('BRL', 'R$'),
    ('BND', '$'),
    ('KHR', '៛'),
    ('CAD', '$'),
    ('KYD', '$'),
    ('CDF', 'FC'),
    ('CLP', '$'),
    ('CNY', '¥'),
    ('COP', '$'),
    ('CRC', '₡'),
    ('CUP', '₱'),
    ('CVE', '$'),
    ('CZK', 'Kč'),
    ('DKK', 'kr'),
    ('DOP', 'RD$'),
    ('DJF', 'Fdj'),
    ('DZD', 'دج'),
    ('XCD', '$'),
    ('EGP', '£'),
    ('SVC', '$'),
    ('ERN', 'Nfk'),
    ('ETB', 'Br'),
    ('EUR', '€'),
    ('FKP', '£'),
    ('FJD', '$'),
    ('GEL', 'ლ'),
    ('GHS', '¢'),
    ('GIP', '£'),
    ('GMD', 'D'),
    ('GTQ', 'Q'),
    ('GGP', '£'),
    ('GNF', 'Fr'),
    ('GYD', '$'),
    ('HNL', 'L'),
    ('HKD', '$'),
    ('HTG', 'G'),
    ('HUF', 'Ft'),
    ('ISK', 'kr'),
    ('INR', '₹'),
    ('IDR', 'Rp'),
    ('IRR', '﷼'),
    ('IMP', '£'),
    ('ILS', '₪'),
    ('IQD', 'د.ع'),
    ('JMD', 'J$'),
    ('JOD', 'د.أ'),
    ('JPY', '¥'),
    ('JEP', '£'),
    ('KES', 'KSh'),
    ('KMF', 'CF'),
    ('KZT', 'лв'),
    ('KPW', '₩'),
    ('KRW', '₩'),
    ('KWD', 'د.ك'),
    ('KGS', 'лв'),
    ('LAK', '₭'),
    ('LBP', '£'),
    ('LRD', '$'),
    ('LSL', 'M'),
    ('LYD', 'ل.د'),
    ('MAD', 'د.إ'),
    ('MDL', 'L'),
    ('MGA', 'Ar'),
    ('MKD', 'ден'),
    ('MMK', 'K'),
    ('MNT', '₮'),
    ('MOP', 'MOP$'),
    ('MRU', 'UM'),
    ('MUR', '₨'),
    ('MVR', 'ރ'),
    ('MWK', 'MK'),
    ('MXN', '$'),
    ('MYR', 'RM'),
    ('MZN', 'MT'),
    ('NAD', '$'),
    ('NPR', '₨'),
    ('ANG', 'ƒ'),
    ('NZD', '$'),
    ('NIO', 'C$'),
    ('NGN', '₦'),
    ('NOK', 'kr'),
    ('OMR', '﷼'),
    ('PAB', 'B/.'),
    ('PEN', 'S/.'),
    ('PGK', 'K'),
    ('PHP', '₱'),
    ('PKR', '₨'),
    ('PLN', 'zł'),
    ('PYG', 'Gs'),
    ('QAR', '﷼'),
    ('RON', 'lei'),
    ('RUB', '₽'),
    ('RWF', 'R₣'),
    ('SHP', '£'),
    ('SAR', '﷼'),
    ('RSD', 'Дин.'),
    ('SBD', '$'),
    ('SCR', '₨'),
    ('SDG', 'ج.س.'),
    ('SGD', '$'),
    ('SLE', 'Le'),
    ('SOS', 'S'),
    ('ZAR', 'R'),
    ('LKR', '₨'),
    ('SEK', 'kr'),
    ('CHF', 'CHF'),
    ('SRD', '$'),
    ('SSP', 'SS£'),
    ('STD', 'Db'),
    ('SYP', '£'),
    ('SZL', 'L'),
    ('THB', '฿'),
    ('TJS', 'SM'),
    ('TMT', 'T'),
    ('TND', 'د.ت'),
    ('TOP', 'T$'),
    ('TRY', '₺'),
    ('TTD', 'TT$'),
    ('TVD', '$'),
    ('TWD', 'NT$'),
    ('TZS', 'TSh'),
    ('UAH', '₴'),
    ('UGX', 'USh'),
    ('AED', 'د.إ'),
    ('GBP', '£'),
    ('USD', '$'),
    ('UYU', '$U'),
    ('UZS', 'лв'),
    ('VEF', 'Bs'),
    ('VES', 'Bs'),
    ('VND', '₫'),
    ('VUV', 'VT'),
    ('WST', '$'),
    ('XAF', 'FCFA'),
    ('XOF', 'CFA'),
    ('XPF', '₣'),
    ('YER', '﷼'),
    ('ZMW', 'ZK'),
    ('ZWD', 'Z$'),
    ('BTC', '₿'),
    ('ETH', 'Ξ');

INSERT INTO continent_ VALUES
    ('AF', 'Africa'),
    ('AS', 'Asia'),
    ('EU', 'Europe'),
    ('NA', 'North America'),
    ('SA', 'South America'),
    ('OC', 'Oceania'),
    ('AN', 'Antarctica');

INSERT INTO country_ ("alpha_2_code", "continent_code", "name", "alpha_3_code", "numeric_3_code", "full_name", "currency_code") VALUES
    ('AF', 'AS', 'Afghanistan', 'AFG', '004', 'Islamic Republic of Afghanistan', 'AFN'),
    ('AX', 'EU', 'Åland Islands', 'ALA', '248', 'Åland Islands', 'EUR'),
    ('AL', 'EU', 'Albania', 'ALB', '008', 'Republic of Albania', 'ALL'),
    ('DZ', 'AF', 'Algeria', 'DZA', '012', 'People''s Democratic Republic of Algeria', 'DZD'),
    ('AS', 'OC', 'American Samoa', 'ASM', '016', 'American Samoa', 'USD'),
    ('AD', 'EU', 'Andorra', 'AND', '020', 'Principality of Andorra', 'EUR'),
    ('AO', 'AF', 'Angola', 'AGO', '024', 'Republic of Angola', 'AOA'),
    ('AI', 'NA', 'Anguilla', 'AIA', '660', 'Anguilla', 'XCD'),
    ('AQ', 'AN', 'Antarctica', 'ATA', '010', 'Antarctica (the territory South of 60 deg S)', 'AAD'),
    ('AG', 'NA', 'Antigua and Barbuda', 'ATG', '028', 'Antigua and Barbuda', 'XCD'),
    ('AR', 'SA', 'Argentina', 'ARG', '032', 'Argentine Republic', 'ARS'),
    ('AM', 'AS', 'Armenia', 'ARM', '051', 'Republic of Armenia', 'AMD'),
    ('AW', 'NA', 'Aruba', 'ABW', '533', 'Aruba', 'AWG'),
    ('AU', 'OC', 'Australia', 'AUS', '036', 'Commonwealth of Australia', 'AUD'),
    ('AT', 'EU', 'Austria', 'AUT', '040', 'Republic of Austria', 'EUR'),
    ('AZ', 'AS', 'Azerbaijan', 'AZE', '031', 'Republic of Azerbaijan', 'AZN'),
    ('BS', 'NA', 'Bahamas', 'BHS', '044', 'Commonwealth of the Bahamas', 'BSD'),
    ('BH', 'AS', 'Bahrain', 'BHR', '048', 'Kingdom of Bahrain', 'BHD'),
    ('BD', 'AS', 'Bangladesh', 'BGD', '050', 'People''s Republic of Bangladesh', 'BDT'),
    ('BB', 'NA', 'Barbados', 'BRB', '052', 'Barbados', 'BBD'),
    ('BY', 'EU', 'Belarus', 'BLR', '112', 'Republic of Belarus', 'BYN'),
    ('BE', 'EU', 'Belgium', 'BEL', '056', 'Kingdom of Belgium', 'EUR'),
    ('BZ', 'NA', 'Belize', 'BLZ', '084', 'Belize', 'BZD'),
    ('BJ', 'AF', 'Benin', 'BEN', '204', 'Republic of Benin', 'XOF'),
    ('BM', 'NA', 'Bermuda', 'BMU', '060', 'Bermuda', 'BMD'),
    ('BT', 'AS', 'Bhutan', 'BTN', '064', 'Kingdom of Bhutan', 'BTN'),
    ('BO', 'SA', 'Bolivia', 'BOL', '068', 'Plurinational State of Bolivia', 'BOB'),
    ('BQ', 'NA', 'Bonaire, Sint Eustatius and Saba', 'BES', '535', 'Bonaire, Sint Eustatius and Saba', 'EUR'),
    ('BA', 'EU', 'Bosnia and Herzegovina', 'BIH', '070', 'Bosnia and Herzegovina', 'BAM'),
    ('BW', 'AF', 'Botswana', 'BWA', '072', 'Republic of Botswana', 'BWP'),
    ('BV', 'AN', 'Bouvet Island (Bouvetøya)', 'BVT', '074', 'Bouvet Island (Bouvetøya)', 'NOK'),
    ('BR', 'SA', 'Brazil', 'BRA', '076', 'Federative Republic of Brazil', 'BRL'),
    ('IO', 'AS', 'British Indian Ocean Territory (Chagos Archipelago)', 'IOT', '086', 'British Indian Ocean Territory (Chagos Archipelago)', 'USD'),
    ('VG', 'NA', 'British Virgin Islands', 'VGB', '092', 'British Virgin Islands', 'USD'),
    ('BN', 'AS', 'Brunei Darussalam', 'BRN', '096', 'Brunei Darussalam', 'BND'),
    ('BG', 'EU', 'Bulgaria', 'BGR', '100', 'Republic of Bulgaria', 'BGN'),
    ('BF', 'AF', 'Burkina Faso', 'BFA', '854', 'Burkina Faso', 'XOF'),
    ('BI', 'AF', 'Burundi', 'BDI', '108', 'Republic of Burundi', 'BIF'),
    ('KH', 'AS', 'Cambodia', 'KHM', '116', 'Kingdom of Cambodia', 'KHR'),
    ('CM', 'AF', 'Cameroon', 'CMR', '120', 'Republic of Cameroon', 'XAF'),
    ('CA', 'NA', 'Canada', 'CAN', '124', 'Canada', 'CAD'),
    ('CV', 'AF', 'Cabo Verde', 'CPV', '132', 'Republic of Cabo Verde', 'CVE'),
    ('KY', 'NA', 'Cayman Islands', 'CYM', '136', 'Cayman Islands', 'KYD'),
    ('CF', 'AF', 'Central African Republic', 'CAF', '140', 'Central African Republic', 'XAF'),
    ('TD', 'AF', 'Chad', 'TCD', '148', 'Republic of Chad', 'XAF'),
    ('CL', 'SA', 'Chile', 'CHL', '152', 'Republic of Chile', 'CLP'),
    ('CN', 'AS', 'China', 'CHN', '156', 'People''s Republic of China', 'CNY'),
    ('CX', 'AS', 'Christmas Island', 'CXR', '162', 'Christmas Island', 'AUD'),
    ('CC', 'AS', 'Cocos (Keeling) Islands', 'CCK', '166', 'Cocos (Keeling) Islands', 'AUD'),
    ('CO', 'SA', 'Colombia', 'COL', '170', 'Republic of Colombia', 'COP'),
    ('KM', 'AF', 'Comoros', 'COM', '174', 'Union of the Comoros', 'KMF'),
    ('CD', 'AF', 'Congo', 'COD', '180', 'Democratic Republic of the Congo', 'CDF'),
    ('CG', 'AF', 'Congo', 'COG', '178', 'Republic of the Congo', 'XOF'),
    ('CK', 'OC', 'Cook Islands', 'COK', '184', 'Cook Islands', 'NZD'),
    ('CR', 'NA', 'Costa Rica', 'CRI', '188', 'Republic of Costa Rica', 'CRC'),
    ('CI', 'AF', 'Cote d''Ivoire', 'CIV', '384', 'Republic of Cote d''Ivoire', 'XOF'),
    ('HR', 'EU', 'Croatia', 'HRV', '191', 'Republic of Croatia', 'EUR'),
    ('CU', 'NA', 'Cuba', 'CUB', '192', 'Republic of Cuba', 'CUP'),
    ('CW', 'NA', 'Curaçao', 'CUW', '531', 'Curaçao', 'ANG'),
    ('CY', 'AS', 'Cyprus', 'CYP', '196', 'Republic of Cyprus', 'EUR'),
    ('CZ', 'EU', 'Czech Republic', 'CZE', '203', 'Czech Republic', 'CZK'),
    ('DK', 'EU', 'Denmark', 'DNK', '208', 'Kingdom of Denmark', 'DKK'),
    ('DJ', 'AF', 'Djibouti', 'DJI', '262', 'Republic of Djibouti', 'DJF'),
    ('DM', 'NA', 'Dominica', 'DMA', '212', 'Commonwealth of Dominica', 'XCD'),
    ('DO', 'NA', 'Dominican Republic', 'DOM', '214', 'Dominican Republic', 'DOP'),
    ('EC', 'SA', 'Ecuador', 'ECU', '218', 'Republic of Ecuador', 'USD'),
    ('EG', 'AF', 'Egypt', 'EGY', '818', 'Arab Republic of Egypt', 'EGP'),
    ('SV', 'NA', 'El Salvador', 'SLV', '222', 'Republic of El Salvador', 'USD'),
    ('GQ', 'AF', 'Equatorial Guinea', 'GNQ', '226', 'Republic of Equatorial Guinea', 'XAF'),
    ('ER', 'AF', 'Eritrea', 'ERI', '232', 'State of Eritrea', 'ERN'),
    ('EE', 'EU', 'Estonia', 'EST', '233', 'Republic of Estonia', 'EUR'),
    ('ET', 'AF', 'Ethiopia', 'ETH', '231', 'Federal Democratic Republic of Ethiopia', 'ETB'),
    ('FO', 'EU', 'Faroe Islands', 'FRO', '234', 'Faroe Islands', 'DKK'),
    ('FK', 'SA', 'Falkland Islands (Malvinas)', 'FLK', '238', 'Falkland Islands (Malvinas)', 'FKP'),
    ('FJ', 'OC', 'Fiji', 'FJI', '242', 'Republic of Fiji', 'FJD'),
    ('FI', 'EU', 'Finland', 'FIN', '246', 'Republic of Finland', 'EUR'),
    ('FR', 'EU', 'France', 'FRA', '250', 'French Republic', 'EUR'),
    ('GF', 'SA', 'French Guiana', 'GUF', '254', 'French Guiana', 'EUR'),
    ('PF', 'OC', 'French Polynesia', 'PYF', '258', 'French Polynesia', 'XPF'),
    ('TF', 'AN', 'French Southern Territories', 'ATF', '260', 'French Southern Territories', 'EUR'),
    ('GA', 'AF', 'Gabon', 'GAB', '266', 'Gabonese Republic', 'XAF'),
    ('GM', 'AF', 'Gambia', 'GMB', '270', 'Republic of the Gambia', 'GMD'),
    ('GE', 'AS', 'Georgia', 'GEO', '268', 'Georgia', 'GEL'),
    ('DE', 'EU', 'Germany', 'DEU', '276', 'Federal Republic of Germany', 'EUR'),
    ('GH', 'AF', 'Ghana', 'GHA', '288', 'Republic of Ghana', 'GHS'),
    ('GI', 'EU', 'Gibraltar', 'GIB', '292', 'Gibraltar', 'GIP'),
    ('GR', 'EU', 'Greece', 'GRC', '300', 'Hellenic Republic of Greece', 'EUR'),
    ('GL', 'NA', 'Greenland', 'GRL', '304', 'Greenland', 'DKK'),
    ('GD', 'NA', 'Grenada', 'GRD', '308', 'Grenada', 'XCD'),
    ('GP', 'NA', 'Guadeloupe', 'GLP', '312', 'Guadeloupe', 'EUR'),
    ('GU', 'OC', 'Guam', 'GUM', '316', 'Guam', 'USD'),
    ('GT', 'NA', 'Guatemala', 'GTM', '320', 'Republic of Guatemala', 'GTQ'),
    ('GG', 'EU', 'Guernsey', 'GGY', '831', 'Bailiwick of Guernsey', 'GGP'),
    ('GN', 'AF', 'Guinea', 'GIN', '324', 'Republic of Guinea', 'GNF'),
    ('GW', 'AF', 'Guinea-Bissau', 'GNB', '624', 'Republic of Guinea-Bissau', 'XOF'),
    ('GY', 'SA', 'Guyana', 'GUY', '328', 'Co-operative Republic of Guyana', 'GYD'),
    ('HT', 'NA', 'Haiti', 'HTI', '332', 'Republic of Haiti', 'HTG'),
    ('HM', 'AN', 'Heard Island and McDonald Islands', 'HMD', '334', 'Heard Island and McDonald Islands', 'AUD'),
    ('HN', 'NA', 'Honduras', 'HND', '340', 'Republic of Honduras', 'HNL'),
    ('HK', 'AS', 'Hong Kong', 'HKG', '344', 'Hong Kong Special Administrative Region of China', 'HKD'),
    ('HU', 'EU', 'Hungary', 'HUN', '348', 'Hungary', 'HUF'),
    ('IS', 'EU', 'Iceland', 'ISL', '352', 'Iceland', 'ISK'),
    ('IN', 'AS', 'India', 'IND', '356', 'Republic of India', 'INR'),
    ('ID', 'AS', 'Indonesia', 'IDN', '360', 'Republic of Indonesia', 'IDR'),
    ('IR', 'AS', 'Iran', 'IRN', '364', 'Islamic Republic of Iran', 'IRR'),
    ('IQ', 'AS', 'Iraq', 'IRQ', '368', 'Republic of Iraq', 'IQD'),
    ('IE', 'EU', 'Ireland', 'IRL', '372', 'Ireland', 'EUR'),
    ('IM', 'EU', 'Isle of Man', 'IMN', '833', 'Isle of Man', 'IMP'),
    ('IL', 'AS', 'Israel', 'ISR', '376', 'State of Israel', 'ILS'),
    ('IT', 'EU', 'Italy', 'ITA', '380', 'Republic of Italy', 'EUR'),
    ('JM', 'NA', 'Jamaica', 'JAM', '388', 'Jamaica', 'JMD'),
    ('JP', 'AS', 'Japan', 'JPN', '392', 'Japan', 'JPY'),
    ('JE', 'EU', 'Jersey', 'JEY', '832', 'Bailiwick of Jersey', 'JEP'),
    ('JO', 'AS', 'Jordan', 'JOR', '400', 'Hashemite Kingdom of Jordan', 'JOD'),
    ('KZ', 'AS', 'Kazakhstan', 'KAZ', '398', 'Republic of Kazakhstan', 'KZT'),
    ('KE', 'AF', 'Kenya', 'KEN', '404', 'Republic of Kenya', 'KES'),
    ('KI', 'OC', 'Kiribati', 'KIR', '296', 'Republic of Kiribati', 'AUD'),
    ('XK', 'EU', 'Kosovo', 'XXK', '926', 'Republic of Kosovo', 'EUR'),
    ('KW', 'AS', 'Kuwait', 'KWT', '414', 'State of Kuwait', 'KWD'),
    ('KG', 'AS', 'Kyrgyzstan', 'KGZ', '417', 'Kyrgyz Republic', 'KGS'),
    ('LA', 'AS', 'Laos', 'LAO', '418', 'Lao People''s Democratic Republic', 'LAK'),
    ('LV', 'EU', 'Latvia', 'LVA', '428', 'Republic of Latvia', 'EUR'),
    ('LB', 'AS', 'Lebanon', 'LBN', '422', 'Lebanese Republic', 'LBP'),
    ('LS', 'AF', 'Lesotho', 'LSO', '426', 'Kingdom of Lesotho', 'LSL'),
    ('LR', 'AF', 'Liberia', 'LBR', '430', 'Republic of Liberia', 'LRD'),
    ('LY', 'AF', 'Libya', 'LBY', '434', 'State of Libya', 'LYD'),
    ('LI', 'EU', 'Liechtenstein', 'LIE', '438', 'Principality of Liechtenstein', 'CHF'),
    ('LT', 'EU', 'Lithuania', 'LTU', '440', 'Republic of Lithuania', 'EUR'),
    ('LU', 'EU', 'Luxembourg', 'LUX', '442', 'Grand Duchy of Luxembourg', 'EUR'),
    ('MO', 'AS', 'Macao', 'MAC', '446', 'Macao Special Administrative Region of China', 'MOP'),
    ('MG', 'AF', 'Madagascar', 'MDG', '450', 'Republic of Madagascar', 'MGA'),
    ('MW', 'AF', 'Malawi', 'MWI', '454', 'Republic of Malawi', 'MWK'),
    ('MY', 'AS', 'Malaysia', 'MYS', '458', 'Malaysia', 'MYR'),
    ('MV', 'AS', 'Maldives', 'MDV', '462', 'Republic of Maldives', 'MVR'),
    ('ML', 'AF', 'Mali', 'MLI', '466', 'Republic of Mali', 'XOF'),
    ('MT', 'EU', 'Malta', 'MLT', '470', 'Republic of Malta', 'EUR'),
    ('MH', 'OC', 'Marshall Islands', 'MHL', '584', 'Republic of the Marshall Islands', 'USD'),
    ('MQ', 'NA', 'Martinique', 'MTQ', '474', 'Martinique', 'EUR'),
    ('MR', 'AF', 'Mauritania', 'MRT', '478', 'Islamic Republic of Mauritania', 'MRU'),
    ('MU', 'AF', 'Mauritius', 'MUS', '480', 'Republic of Mauritius', 'MUR'),
    ('YT', 'AF', 'Mayotte', 'MYT', '175', 'Mayotte', 'EUR'),
    ('MX', 'NA', 'Mexico', 'MEX', '484', 'United Mexican States', 'MXN'),
    ('FM', 'OC', 'Micronesia', 'FSM', '583', 'Federated States of Micronesia', 'USD'),
    ('MD', 'EU', 'Moldova', 'MDA', '498', 'Republic of Moldova', 'MDL'),
    ('MC', 'EU', 'Monaco', 'MCO', '492', 'Principality of Monaco', 'EUR'),
    ('MN', 'AS', 'Mongolia', 'MNG', '496', 'Mongolia', 'MNT'),
    ('ME', 'EU', 'Montenegro', 'MNE', '499', 'Montenegro', 'EUR'),
    ('MS', 'NA', 'Montserrat', 'MSR', '500', 'Montserrat', 'XCD'),
    ('MA', 'AF', 'Morocco', 'MAR', '504', 'Kingdom of Morocco', 'MAD'),
    ('MZ', 'AF', 'Mozambique', 'MOZ', '508', 'Republic of Mozambique', 'MZN'),
    ('MM', 'AS', 'Myanmar', 'MMR', '104', 'Republic of the Union of Myanmar', 'MMK'),
    ('NA', 'AF', 'Namibia', 'NAM', '516', 'Republic of Namibia', 'NAD'),
    ('NR', 'OC', 'Nauru', 'NRU', '520', 'Republic of Nauru', 'AUD'),
    ('NP', 'AS', 'Nepal', 'NPL', '524', 'Nepal', 'NPR'),
    ('NL', 'EU', 'Netherlands', 'NLD', '528', 'Kingdom of the Netherlands', 'EUR'),
    ('NC', 'OC', 'New Caledonia', 'NCL', '540', 'New Caledonia', 'XPF'),
    ('NZ', 'OC', 'New Zealand', 'NZL', '554', 'New Zealand', 'NZD'),
    ('NI', 'NA', 'Nicaragua', 'NIC', '558', 'Republic of Nicaragua', 'NIO'),
    ('NE', 'AF', 'Niger', 'NER', '562', 'Republic of Niger', 'XOF'),
    ('NG', 'AF', 'Nigeria', 'NGA', '566', 'Federal Republic of Nigeria', 'NGN'),
    ('NU', 'OC', 'Niue', 'NIU', '570', 'Niue', 'NZD'),
    ('NF', 'OC', 'Norfolk Island', 'NFK', '574', 'Norfolk Island', 'AUD'),
    ('KP', 'AS', 'North Korea', 'PRK', '408', 'Democratic People''s Republic of Korea', 'KPW'),
    ('MK', 'EU', 'North Macedonia', 'MKD', '807', 'Republic of North Macedonia', 'MKD'),
    ('MP', 'OC', 'Northern Mariana Islands', 'MNP', '580', 'Commonwealth of the Northern Mariana Islands', 'USD'),
    ('NO', 'EU', 'Norway', 'NOR', '578', 'Kingdom of Norway', 'NOK'),
    ('OM', 'AS', 'Oman', 'OMN', '512', 'Sultanate of Oman', 'OMR'),
    ('PK', 'AS', 'Pakistan', 'PAK', '586', 'Islamic Republic of Pakistan', 'PKR'),
    ('PW', 'OC', 'Palau', 'PLW', '585', 'Republic of Palau', 'USD'),
    ('PS', 'AS', 'Palestine', 'PSE', '275', 'State of Palestine', 'ILS'),
    ('PA', 'NA', 'Panama', 'PAN', '591', 'Republic of Panama', 'PAB'),
    ('PG', 'OC', 'Papua New Guinea', 'PNG', '598', 'Independent State of Papua New Guinea', 'PGK'),
    ('PY', 'SA', 'Paraguay', 'PRY', '600', 'Republic of Paraguay', 'PYG'),
    ('PE', 'SA', 'Peru', 'PER', '604', 'Republic of Peru', 'PEN'),
    ('PH', 'AS', 'Philippines', 'PHL', '608', 'Republic of the Philippines', 'PHP'),
    ('PN', 'OC', 'Pitcairn Islands', 'PCN', '612', 'Pitcairn Islands', 'NZD'),
    ('PL', 'EU', 'Poland', 'POL', '616', 'Republic of Poland', 'PLN'),
    ('PT', 'EU', 'Portugal', 'PRT', '620', 'Portuguese Republic', 'EUR'),
    ('PR', 'NA', 'Puerto Rico', 'PRI', '630', 'Commonwealth of Puerto Rico', 'USD'),
    ('QA', 'AS', 'Qatar', 'QAT', '634', 'State of Qatar', 'QAR'),
    ('RE', 'AF', 'Réunion', 'REU', '638', 'Réunion', 'EUR'),
    ('RO', 'EU', 'Romania', 'ROU', '642', 'Romania', 'RON'),
    ('RU', 'EU', 'Russia', 'RUS', '643', 'Russian Federation', 'RUB'),
    ('RW', 'AF', 'Rwanda', 'RWA', '646', 'Republic of Rwanda', 'RWF'),
    ('BL', 'NA', 'Saint Barthélemy', 'BLM', '652', 'Saint Barthélemy', 'EUR'),
    ('SH', 'AF', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha', 'SHP'),
    ('KN', 'NA', 'Saint Kitts and Nevis', 'KNA', '659', 'Federation of Saint Kitts and Nevis', 'XCD'),
    ('LC', 'NA', 'Saint Lucia', 'LCA', '662', 'Saint Lucia', 'XCD'),
    ('MF', 'NA', 'Saint Martin', 'MAF', '663', 'Saint Martin (French part)', 'EUR'),
    ('PM', 'NA', 'Saint Pierre and Miquelon', 'SPM', '666', 'Saint Pierre and Miquelon', 'EUR'),
    ('VC', 'NA', 'Saint Vincent and the Grenadines', 'VCT', '670', 'Saint Vincent and the Grenadines', 'XCD'),
    ('WS', 'OC', 'Samoa', 'WSM', '882', 'Independent State of Samoa', 'WST'),
    ('SM', 'EU', 'San Marino', 'SMR', '674', 'Republic of San Marino', 'EUR'),
    ('ST', 'AF', 'Sao Tome and Principe', 'STP', '678', 'Democratic Republic of Sao Tome and Principe', 'STD'),
    ('SA', 'AS', 'Saudi Arabia', 'SAU', '682', 'Kingdom of Saudi Arabia', 'SAR'),
    ('SN', 'AF', 'Senegal', 'SEN', '686', 'Republic of Senegal', 'XOF'),
    ('RS', 'EU', 'Serbia', 'SRB', '688', 'Republic of Serbia', 'RSD'),
    ('SC', 'AF', 'Seychelles', 'SYC', '690', 'Republic of Seychelles', 'SCR'),
    ('SL', 'AF', 'Sierra Leone', 'SLE', '694', 'Republic of Sierra Leone', 'SLE'),
    ('SG', 'AS', 'Singapore', 'SGP', '702', 'Republic of Singapore', 'SGD'),
    ('SX', 'NA', 'Sint Maarten', 'SXM', '534', 'Sint Maarten (Dutch part)', 'ANG'),
    ('SK', 'EU', 'Slovakia', 'SVK', '703', 'Slovakia (Slovak Republic)', 'EUR'),
    ('SI', 'EU', 'Slovenia', 'SVN', '705', 'Republic of Slovenia', 'EUR'),
    ('SB', 'OC', 'Solomon Islands', 'SLB', '090', 'Solomon Islands', 'SBD'),
    ('SO', 'AF', 'Somalia', 'SOM', '706', 'Federal Republic of Somalia', 'SOS'),
    ('ZA', 'AF', 'South Africa', 'ZAF', '710', 'Republic of South Africa', 'ZAR'),
    ('GS', 'AN', 'South Georgia and the South Sandwich Islands', 'SGS', '239', 'South Georgia and the South Sandwich Islands', 'FKP'),
    ('KR', 'AS', 'South Korea', 'KOR', '410', 'Republic of Korea', 'KRW'),
    ('SS', 'AF', 'South Sudan', 'SSD', '728', 'Republic of South Sudan', 'SSP'),
    ('ES', 'EU', 'Spain', 'ESP', '724', 'Kingdom of Spain', 'EUR'),
    ('LK', 'AS', 'Sri Lanka', 'LKA', '144', 'Democratic Socialist Republic of Sri Lanka', 'SDG'),
    ('SD', 'AF', 'Sudan', 'SDN', '729', 'Republic of Sudan', 'SDG'),
    ('SR', 'SA', 'Suriname', 'SUR', '740', 'Republic of Suriname', 'SRD'),
    ('SJ', 'EU', 'Svalbard and Jan Mayen Islands', 'SJM', '744', 'Svalbard and Jan Mayen Islands', 'NOK'),
    ('SZ', 'AF', 'Eswatini', 'SWZ', '748', 'Kingdom of Eswatini', 'SZL'),
    ('SE', 'EU', 'Sweden', 'SWE', '752', 'Kingdom of Sweden', 'SEK'),
    ('CH', 'EU', 'Switzerland', 'CHE', '756', 'Swiss Confederation', 'CHF'),
    ('SY', 'AS', 'Syria', 'SYR', '760', 'Syrian Arab Republic', 'SYP'),
    ('TW', 'AS', 'Taiwan', 'TWN', '158', 'Taiwan, Province of China', 'TWD'),
    ('TJ', 'AS', 'Tajikistan', 'TJK', '762', 'Republic of Tajikistan', 'TJS'),
    ('TZ', 'AF', 'Tanzania', 'TZA', '834', 'United Republic of Tanzania', 'TZS'),
    ('TH', 'AS', 'Thailand', 'THA', '764', 'Kingdom of Thailand', 'THB'),
    ('TL', 'AS', 'Timor-Leste', 'TLS', '626', 'Democratic Republic of Timor-Leste', 'USD'),
    ('TG', 'AF', 'Togo', 'TGO', '768', 'Togolese Republic', 'XOF'),
    ('TK', 'OC', 'Tokelau', 'TKL', '772', 'Tokelau', 'NZD'),
    ('TO', 'OC', 'Tonga', 'TON', '776', 'Kingdom of Tonga', 'TOP'),
    ('TT', 'NA', 'Trinidad and Tobago', 'TTO', '780', 'Republic of Trinidad and Tobago', 'TTD'),
    ('TN', 'AF', 'Tunisia', 'TUN', '788', 'Tunisian Republic', 'TND'),
    ('TR', 'AS', 'Türkiye', 'TUR', '792', 'Republic of Türkiye', 'TRY'),
    ('TM', 'AS', 'Turkmenistan', 'TKM', '795', 'Turkmenistan', 'TMT'),
    ('TC', 'NA', 'Turks and Caicos Islands', 'TCA', '796', 'Turks and Caicos Islands', 'USD'),
    ('TV', 'OC', 'Tuvalu', 'TUV', '798', 'Tuvalu', 'AUD'),
    ('UG', 'AF', 'Uganda', 'UGA', '800', 'Republic of Uganda', 'UGX'),
    ('UA', 'EU', 'Ukraine', 'UKR', '804', 'Ukraine', 'UAH'),
    ('AE', 'AS', 'United Arab Emirates', 'ARE', '784', 'United Arab Emirates', 'AED'),
    ('GB', 'EU', 'United Kingdom', 'GBR', '826', 'United Kingdom of Great Britain & Northern Ireland', 'GBP'),
    ('US', 'NA', 'United States', 'USA', '840', 'United States of America', 'USD'),
    ('UM', 'OC', 'United States Minor Outlying Islands', 'UMI', '581', 'United States Minor Outlying Islands', 'USD'),
    ('VI', 'NA', 'U.S. Virgin Islands', 'VIR', '850', 'United States Virgin Islands', 'USD'),
    ('UY', 'SA', 'Uruguay', 'URY', '858', 'Eastern Republic of Uruguay', 'UYU'),
    ('UZ', 'AS', 'Uzbekistan', 'UZB', '860', 'Republic of Uzbekistan', 'UZS'),
    ('VU', 'OC', 'Vanuatu', 'VUT', '548', 'Republic of Vanuatu', 'VUV'),
    ('VA', 'EU', 'Vatican City', 'VAT', '336', 'Holy See (Vatican City State)', 'EUR'),
    ('VE', 'SA', 'Venezuela', 'VEN', '862', 'Bolivarian Republic of Venezuela', 'VES'),
    ('VN', 'AS', 'Vietnam', 'VNM', '704', 'Socialist Republic of Vietnam', 'VND'),
    ('WF', 'OC', 'Wallis and Futuna', 'WLF', '876', 'Wallis and Futuna', 'XPF'),
    ('EH', 'AF', 'Western Sahara', 'ESH', '732', 'Western Sahara', 'MAD'),
    ('YE', 'AS', 'Yemen', 'YEM', '887', 'Yemen', 'YER'),
    ('ZM', 'AF', 'Zambia', 'ZMB', '894', 'Republic of Zambia', 'ZMW'),
    ('ZW', 'AF', 'Zimbabwe', 'ZWE', '716', 'Republic of Zimbabwe', 'ZWD');

INSERT INTO country_dialing_code_ ("alpha_2_code", "code") VALUES
    ('AF', '93'),
    ('AX', '358'),
    ('AL', '355'),
    ('DZ', '213'),
    ('AS', '1684'),
    ('AD', '376'),
    ('AO', '244'),
    ('AI', '1264'),
    ('AQ', '672'),
    ('AG', '1268'),
    ('AR', '54'),
    ('AM', '374'),
    ('AW', '297'),
    ('AU', '61'),
    ('AT', '43'),
    ('AZ', '994'),
    ('BS', '1242'),
    ('BH', '973'),
    ('BD', '880'),
    ('BB', '1246'),
    ('BY', '375'),
    ('BE', '32'),
    ('BZ', '501'),
    ('BJ', '229'),
    ('BM', '1441'),
    ('BT', '975'),
    ('BO', '591'),
    ('BQ', '5994'),
    ('BA', '387'),
    ('BW', '267'),
    ('BV', '47'),
    ('BR', '55'),
    ('IO', '246'),
    ('BN', '673'),
    ('BG', '359'),
    ('BF', '226'),
    ('BI', '257'),
    ('KH', '855'),
    ('CM', '237'),
    ('CA', '1'),
    ('CV', '238'),
    ('KY', '1345'),
    ('CF', '236'),
    ('TD', '235'),
    ('CL', '56'),
    ('CN', '86'),
    ('CX', '61'),
    ('CC', '61'),
    ('CO', '57'),
    ('KM', '269'),
    ('CG', '242'),
    ('CD', '243'),
    ('CK', '682'),
    ('CR', '506'),
    ('CI', '225'),
    ('HR', '385'),
    ('CU', '53'),
    ('CW', '5999'),
    ('CY', '357'),
    ('CZ', '420'),
    ('DK', '45'),
    ('DJ', '253'),
    ('DM', '1767'),
    ('DO', '1809'),
    ('DO', '1829'),
    ('DO', '1849'),
    ('EC', '593'),
    ('EG', '20'),
    ('SV', '503'),
    ('GQ', '240'),
    ('ER', '291'),
    ('EE', '372'),
    ('ET', '251'),
    ('FK', '500'),
    ('FO', '298'),
    ('FJ', '679'),
    ('FI', '358'),
    ('FR', '33'),
    ('GF', '594'),
    ('PF', '689'),
    ('TF', '962'),
    ('GA', '241'),
    ('GM', '220'),
    ('GE', '995'),
    ('DE', '49'),
    ('GH', '233'),
    ('GI', '350'),
    ('GR', '30'),
    ('GL', '299'),
    ('GD', '1473'),
    ('GP', '590'),
    ('GU', '1671'),
    ('GT', '502'),
    ('GG', '441481'),
    ('GN', '224'),
    ('GW', '245'),
    ('GY', '592'),
    ('HT', '509'),
    ('HM', '0'),
    ('HN', '504'),
    ('HK', '852'),
    ('HU', '36'),
    ('IS', '354'),
    ('IN', '91'),
    ('ID', '62'),
    ('IR', '98'),
    ('IQ', '964'),
    ('IE', '353'),
    ('IM', '441624'),
    ('IL', '972'),
    ('IT', '39'),
    ('JM', '1876'),
    ('JP', '81'),
    ('JE', '441534'),
    ('JO', '962'),
    ('KZ', '7'),
    ('KE', '254'),
    ('KI', '686'),
    ('KP', '850'),
    ('KR', '82'),
    ('XK', '383'),
    ('KW', '965'),
    ('KG', '996'),
    ('LA', '856'),
    ('LV', '371'),
    ('LB', '961'),
    ('LS', '266'),
    ('LR', '231'),
    ('LY', '218'),
    ('LI', '423'),
    ('LT', '370'),
    ('LU', '352'),
    ('MO', '853'),
    ('MK', '389'),
    ('MG', '261'),
    ('MW', '265'),
    ('MY', '60'),
    ('MV', '960'),
    ('ML', '223'),
    ('MT', '356'),
    ('MH', '692'),
    ('MQ', '596'),
    ('MR', '222'),
    ('MU', '230'),
    ('YT', '262'),
    ('MX', '52'),
    ('FM', '691'),
    ('MD', '373'),
    ('MC', '377'),
    ('MN', '976'),
    ('ME', '382'),
    ('MS', '1664'),
    ('MA', '212'),
    ('MZ', '258'),
    ('MM', '95'),
    ('NA', '264'),
    ('NR', '674'),
    ('NP', '977'),
    ('NL', '31'),
    ('NC', '687'),
    ('NZ', '64'),
    ('NI', '505'),
    ('NE', '227'),
    ('NG', '234'),
    ('NU', '683'),
    ('NF', '672'),
    ('MP', '1670'),
    ('NO', '47'),
    ('OM', '968'),
    ('PK', '92'),
    ('PW', '680'),
    ('PS', '970'),
    ('PA', '507'),
    ('PG', '675'),
    ('PY', '595'),
    ('PE', '51'),
    ('PH', '63'),
    ('PN', '64'),
    ('PL', '48'),
    ('PT', '351'),
    ('PR', '1787'),
    ('PR', '1939'),
    ('QA', '974'),
    ('RE', '262'),
    ('RO', '40'),
    ('RU', '7'),
    ('RW', '250'),
    ('BL', '590'),
    ('SH', '290'),
    ('KN', '1869'),
    ('LC', '1758'),
    ('MF', '590'),
    ('PM', '508'),
    ('VC', '1784'),
    ('WS', '685'),
    ('SM', '378'),
    ('ST', '239'),
    ('SA', '966'),
    ('SN', '221'),
    ('RS', '381'),
    ('SC', '248'),
    ('SL', '232'),
    ('SG', '65'),
    ('SX', '1721'),
    ('SK', '421'),
    ('SI', '386'),
    ('SB', '677'),
    ('SO', '252'),
    ('ZA', '27'),
    ('GS', '500'),
    ('SS', '211'),
    ('ES', '34'),
    ('LK', '94'),
    ('SD', '249'),
    ('SR', '597'),
    ('SJ', '47'),
    ('SZ', '268'),
    ('SE', '46'),
    ('CH', '41'),
    ('SY', '963'),
    ('TW', '886'),
    ('TJ', '992'),
    ('TZ', '255'),
    ('TH', '66'),
    ('TL', '670'),
    ('TG', '228'),
    ('TK', '690'),
    ('TO', '676'),
    ('TT', '1868'),
    ('TN', '216'),
    ('TR', '90'),
    ('TM', '993'),
    ('TC', '1649'),
    ('TV', '688'),
    ('UG', '256'),
    ('UA', '380'),
    ('AE', '971'),
    ('GB', '44'),
    ('US', '1'),
    ('UY', '598'),
    ('UZ', '998'),
    ('VU', '678'),
    ('VA', '379'),
    ('VE', '58'),
    ('VN', '84'),
    ('VG', '1284'),
    ('UM', '1'),
    ('VI', '1340'),
    ('WF', '681'),
    ('EH', '212'),
    ('YE', '967'),
    ('ZM', '260'),
    ('ZW', '263');
